name: Terraform GCS Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-gcs

    - name: Terraform Plan
      run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="bucket_name=${{ secrets.GCP_BUCKET_NAME }}"
      working-directory: ./terraform-gcs

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="bucket_name=${{ secrets.GCP_BUCKET_NAME }}"
      working-directory: ./terraform-gcs
